<?xml version="1.0"?>
<!--
  Copyright 2015 Fadri Furrer, ASL, ETH Zurich, Switzerland
  Copyright 2015 Michael Burri, ASL, ETH Zurich, Switzerland
  Copyright 2015 Mina Kamel, ASL, ETH Zurich, Switzerland
  Copyright 2015 Janosch Nikolic, ASL, ETH Zurich, Switzerland
  Copyright 2015 Markus Achtelik, ASL, ETH Zurich, Switzerland

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<robot xmlns:xacro="http://ros.org/wiki/xacro">


  <!-- Property Blocks -->

  <!-- Rigid body (load) -->

  <xacro:property name="rb_inertia">
    <inertia
    ixx="${1/12 * rb_mass * (rb_height * rb_height + rb_width * rb_width)}"
    iyy="${1/12 * rb_mass * (rb_length * rb_length + rb_height * rb_height)}"
    izz="${1/12 * rb_mass * (rb_length * rb_length + rb_width * rb_width)}"
    ixy="0.0" ixz="0.0" iyz="0.0" /> <!-- [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] -->
  </xacro:property>

  <!-- Cable -->

  <xacro:property name="cable_attachment_origin">
    <origin xyz="0.0 0.0 ${cable_length/2}" />
  </xacro:property>

  <xacro:property name="cable_inertia">
    <inertia
    ixx="${1/12 * cable_mass * (cable_length * cable_length + cable_width * cable_width)}"
    iyy="${1/12 * cable_mass * (cable_length * cable_length + cable_width * cable_width)}"
    izz="${1/12 * cable_mass * (cable_width * cable_width + cable_width * cable_width)}"
    ixy="0.0" ixz="0.0" iyz="0.0" /> <!-- [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] -->
  </xacro:property>

  <xacro:property name="fake_joint_inertia">
    <inertia
    ixx="1e-03"
    iyy="1e-03"
    izz="1e-03"
    ixy="0.0" ixz="0.0" iyz="0.0" /> <!-- [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] -->
  </xacro:property>

  <!-- Quad  -->

  <xacro:property name="quad_inertia">
    <inertia
    ixx="${1/12 * quad_mass * (quad_height * quad_height + quad_width * quad_width)}"
    iyy="${1/12 * quad_mass * (quad_length * quad_length + quad_height * quad_height)}"
    izz="${1/12 * quad_mass * (quad_length * quad_length + quad_width * quad_width)}"
    ixy="0.0" ixz="0.0" iyz="0.0" /> <!-- [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] [kg.m^2] -->
  </xacro:property>

  <!-- Macro Blocks -->

  <!-- Cable Macro -->

  <xacro:macro name="cable_macro"
    params="parent child cable_number *attachment_point">

    <xacro:spherical_joint_xy
       parent_link="${parent}"
       child_link="cable_link_${cable_number}">
       <xacro:insert_block name="attachment_point" />
    </xacro:spherical_joint_xy>

    <xacro:spherical_joint_xy
       parent_link="cable_link_${cable_number}"
       child_link="${child}">
       <origin xyz="0.0 0.0 ${cable_length}" />
    </xacro:spherical_joint_xy>

    <link name="cable_link_${cable_number}">
      <inertial>
        <xacro:insert_block name="cable_attachment_origin" />
        <mass value="${cable_mass}" />  <!-- [kg] -->
        <xacro:insert_block name="cable_inertia" />
      </inertial>

      <visual>
        <xacro:insert_block name="cable_attachment_origin" />
        <geometry>
          <box size="${cable_width} ${cable_width} ${cable_length}"/> <!-- [m] [m] [m] -->
        </geometry>
      </visual>

      <!-- <collision>
        <geometry>
          <box size="${cable_length} ${cable_width} ${cable_length}" />
        </geometry>
      </collision> -->
    </link>

  </xacro:macro>

  <!-- Spherical joint emulation Macro -->

  <xacro:macro name="spherical_joint_xy"
    params="parent_link child_link *attachment_point">

    <link name="fake_joint_${parent_link}_${child_link}">
        <inertial>
            <mass value="${fake_joint_mass}" />  <!-- [kg] -->
            <xacro:insert_block name="fake_joint_inertia" />
        </inertial>
        <!-- <visual>
          <geometry>
            <sphere radius="${0.01}"/>
          </geometry>
        </visual> -->
    </link>

    <joint name="fake_joint_${parent_link}_${child_link}_x" type="continuous">
      <xacro:insert_block name="attachment_point" />
      <axis xyz="1 0 0" />
      <parent link="${parent_link}" />
      <child link="fake_joint_${parent_link}_${child_link}" />
    </joint>

    <joint name="fake_joint_${parent_link}_${child_link}_y" type="continuous">
      <axis xyz="0 1 0" />
      <parent link="fake_joint_${parent_link}_${child_link}" />
      <child link="${child_link}" />
    </joint>
  </xacro:macro>

  <!-- Quadrotor macro -->

    <xacro:macro name="quad_macro"
    params="quad_number">

    <link name="quad_link_${quad_number}">
      <inertial>
        <mass value="${quad_mass}" />  <!-- [kg] -->
        <xacro:insert_block name="quad_inertia" />
      </inertial>

      <visual>
        <geometry>
          <box size="${quad_length} ${quad_width} ${quad_height}"/> <!-- [m] [m] [m] -->
        </geometry>
      </visual>

      <collision>
        <geometry>
          <box size="${quad_length} ${quad_width} ${quad_height}"/> <!-- [m] [m] [m] -->
        </geometry>
      </collision>
    </link>

  </xacro:macro>

  <!-- Rigid-body (load) Macro -->

  <xacro:macro name="rb_load_macro"
    params="rb_mass rb_length rb_width rb_height cable_mass cable_length cable_width quad_mass quad_length quad_width quad_height fake_joint_mass">

    <link name="rb_link">
      <inertial>
        <mass value="${rb_mass}" />  <!-- [kg] -->
        <origin xyz="0 0 0" />
        <xacro:insert_block name="rb_inertia" />
      </inertial>

      <visual>
        <geometry>
          <box size="${rb_length} ${rb_width} ${rb_height}"/> <!-- [m] [m] [m] -->
        </geometry>
      </visual>

      <!-- <collision>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <sphere radius="${load_radius}"/>
        </geometry>
      </collision> -->
    </link>

    <!-- Four quadrotors -->

    <!-- <xacro:cable_macro parent="rb_link" cable_number="0">
      <origin xyz="${rb_length/2} ${rb_width/2} ${rb_height/2}" />
    </xacro:cable_macro>

    <xacro:cable_macro parent="rb_link" cable_number="1">
      <origin xyz="${-rb_length/2} ${rb_width/2} ${rb_height/2}" />
    </xacro:cable_macro>

    <xacro:cable_macro parent="rb_link" cable_number="2">
      <origin xyz="${-rb_length/2} ${-rb_width/2} ${rb_height/2}" />
    </xacro:cable_macro>

    <xacro:cable_macro parent="rb_link" cable_number="3">
      <origin xyz="${rb_length/2} ${-rb_width/2} ${rb_height/2}" />
    </xacro:cable_macro> -->

    <!-- Three quadrotors -->

    <xacro:quad_macro quad_number="0">
    </xacro:quad_macro>

    <xacro:quad_macro quad_number="1">
    </xacro:quad_macro>

    <xacro:quad_macro quad_number="2">
    </xacro:quad_macro>

    <xacro:cable_macro parent="rb_link" child="quad_link_0" cable_number="0">
      <origin xyz="${rb_length/2} ${-rb_width/2} ${rb_height/2}" />
    </xacro:cable_macro>

    <xacro:cable_macro parent="rb_link" child="quad_link_1" cable_number="1">
      <origin xyz="${rb_length/2} ${rb_width/2} ${rb_height/2}" />
    </xacro:cable_macro>

    <xacro:cable_macro parent="rb_link" child="quad_link_2" cable_number="2">
      <origin xyz="${-rb_length/2} ${0} ${rb_height/2}" />
    </xacro:cable_macro>


  </xacro:macro>




</robot>
